#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=TestMCTSJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=12:00:00
#SBATCH --output=logs/test_mcts_job_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate lean-reinforcement

# Set environment variables
export MATHLIB4_DATASET_PATH=$HOME/lean_reinforcement/data/mathlib4_traced

cd $HOME/lean_reinforcement/src
srun python test_mcts.py
