#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=LoadData
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=logs/load_data_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate lean-reinforcement

# Source environment variables
set -a
source $HOME/lean_reinforcement/.env
set +a

# Ensure cache directory exists
mkdir -p "${CACHE_DIR}"

cd $HOME/lean_reinforcement/lean_reinforcement
srun python testing.py
