#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=TraceRepoJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=logs/trace_repo_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate lean-reinforcement

# Source environment variables
set -a
source $HOME/lean_reinforcement/.env
set +a

# Ensure cache directory exists
mkdir -p "${CACHE_DIR}"

cd $HOME/lean_reinforcement/src
srun python trace_repo.py
