#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=ValidateCache
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=logs/test_transformer_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate lean-reinforcement

# Source environment variables
set -a
source $HOME/lean_reinforcement/.env
set +a

cd $HOME/lean_reinforcement/scripts

# Run comprehensive tests
srun python validate_cache.py